#!/usr/bin/perl
# Spawn a new terminal in the current directory using Ctrl-Shift-N:
# 
# URxvt.perl-ext-common: newterm
# URxvt.keysym.C-S-N: perl:newterm
#
# Copyright (C) 2013  Christopher Johnson
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

sub on_user_command {
    my ($term, $string) = @_;

    # Check that keysym was "perl:newterm"
    if ($string eq "newterm") {
        my $dir = readlink("/proc/" . $term->{child_pid} . "/cwd");
        exec("urxvt", "-cd", "$dir") unless fork;
    }
    ()
}

sub on_child_start {
    my ($term, $pid) = @_;
    $term->{child_pid} = $pid;
    ()
}
