#!/usr/bin/env bash
########################################################
#
#    ▄█    █▄     ▄█        ▄█     █▄    ▄▄▄▄███▄▄▄▄
#   ███    ███   ███       ███     ███ ▄██▀▀▀███▀▀▀██▄
#   ███    ███   ███       ███     ███ ███   ███   ███
#  ▄███▄▄▄▄███▄▄ ███       ███     ███ ███   ███   ███
# ▀▀███▀▀▀▀███▀  ███       ███     ███ ███   ███   ███
#   ███    ███   ███       ███     ███ ███   ███   ███
#   ███    ███   ███▌    ▄ ███ ▄█▄ ███ ███   ███   ███
#   ███    █▀    █████▄▄██  ▀███▀███▀   ▀█   ███   █▀
#                ▀
#
#######################################################
# Make interrupt signals do nothing.
trap '' INT TSTP

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# Always wanted for refresh
noisewall "#452f2f"
#hsetroot -center ~/Pictures/muspelheim_dore.png

# remove all existing keybindings
hc keyunbind --all

# Basics
hc keybind Mod4-Return or ',' and '.' compare tags.focus.frame_count = 1 '.' compare tags.focus.curframe_wcount = 0 '.' spawn urxvtdc ',' and '_' compare tags.focus.curframe_wcount = 0 '_' spawn urxvtdc ',' chain '-' split auto '-' cycle_frame '-' spawn urxvtdc #bsp-like spawning of terminal

hc keybind Mod4-Shift-Return spawn urxvtdc                                    #Spawn terminal
hc keybind Mod4-e spawn launch                                                #Launcher
hc keybind Mod4-Shift-e spawn power                                           #Power menu
hc keybind Mod4-d spawn hlscrthpd.sh                                          #Dropdown terminal
hc keybind Mod4-space spawn task.sh                                           #Tasklist
hc keybind Mod4-a spawn ~/.config/herbstluftwm/scripts/key_help.sh            #Keybinding help
hc keybind Mod4-Shift-a spawn urxvtdc -e vim ~/.config/herbstluftwm/autostart #Edit hlwm config

# Window info/wm ctrls
hc keybind Mod4-w spawn rofi -show window                               #Switch windows
hc keybind Mod4-Control-w spawn ~/.config/herbstluftwm/toggle_titles.sh #Toggle window titles
hc keybind Mod4-Shift-r reload                                          #Reload hlwm

# Toggles
hc keybind Mod4-b spawn togglebar.sh            #Toggle bar
hc keybind Mod4-Shift-p spawn togglepicom       #Toggle compositor
hc keybind XF86Launch1 spawn toggle_touchpad.sh #Toggle touchpad
hc keybind XF86Display spawn caffeine.sh        #Toggle caffeine
#hc keybind Mod4-Shift-n spawn toggledunst     #Toggle notifications
#hc keybind XF86Tools spawn toggle_redshift.sh #Toggle redshift

# Utilities
hc keybind Mod4-u spawn unmount.sh                    #Unmount drives
hc keybind XF86Favorites spawn prtscr                 #Print Screen
hc keybind Mod4-XF86Favorites spawn prtregion         #Print region
hc keybind Mod4-x spawn clipmenu -p 'Clipboard:' -l 0 #Clipboard manager
hc keybind Mod4-Shift-c spawn colorpicker.sh          #Colorpicker
hc keybind Mod4-Shift-z spawn xcolor -c ""            #Zoom
hc keybind Mod4-Shift-m spawn emote                   #Kaomoji selector
hc keybind Mod4-z spawn mwarp.sh                      #Warp mouse

# Notification controls
hc keybind Control-grave spawn notif_hist.sh -q #Query last notification
hc keybind Control-space spawn notif_hist.sh -c #Close all notification history

# Volume/Brightness keys
hc keybind XF86MonBrightnessUp spawn bright up     #Increase brightness
hc keybind XF86MonBrightnessDown spawn bright down #Decrease brightness

hc keybind XF86AudioRaiseVolume spawn vol alsa up           #Increase Volume
hc keybind XF86AudioLowerVolume spawn vol alsa down         #Decrease volume
hc keybind XF86AudioMute spawn vol alsa mute                #Mute audio
hc keybind Mod4-XF86AudioLowerVolume spawn vol alsamic down #Decrease mic volume
hc keybind XF86AudioMicMute spawn vol alsamic mute          #mute mic

# Player controls
hc keybind Mod4-Control-Mod1-h spawn playerctl previous   #Previous audio
hc keybind Mod4-Control-Mod1-l spawn playerctl next       #Next audio
hc keybind Mod4-Control-Mod1-k spawn playerctl play-pause #Toggle play/pause audio
hc keybind Mod4-Control-Mod1-j spawn playerctl stop       #Stop audio

# Window/frame controls
hc keybind Mod4-q close                                                    #Close focused window
hc keybind Mod4-Shift-q close_and_remove                                   #Close window and frame if last window
hc keybind Mod4-m spawn ~/.config/herbstluftwm/scripts/maximize.sh         #Alternate tiled and monocle layout
hc keybind Mod4-i jumpto urgent                                            #Jump to urgent window
hc keybind Mod4-Shift-s spawn ~/.config/herbstluftwm//scripts/savestate.sh #Save current session
hc keybind Mod4-Tab cycle                                                  #Circulate focus on windows in frame
hc keybind Mod4-Shift-Tab cycle -1                                         #Circulate focus on windows in frame in reverse
hc keybind Mod4-grave cycle_monitor                                        #Circulate monitor focus

# focusing clients
hc keybind Mod4-h focus left  #Focus left
hc keybind Mod4-j focus down  #Focus down
hc keybind Mod4-k focus up    #focus up
hc keybind Mod4-l focus right #Focus right

# moving clients
hc keybind Mod4-Shift-h shift left  #Move window left
hc keybind Mod4-Shift-j shift down  #Move window down
hc keybind Mod4-Shift-k shift up    #Move window up
hc keybind Mod4-Shift-l shift right #Move window right

# Cycle focus through tags
hc keybind Mod4-period ~/.config/herbstluftwm/scripts/tag_switch.sh next #Switch to next non-empty tag

hc keybind Mod4-comma ~/.config/herbstluftwm/scripts/tag_switch.sh prev #Switch to prev non-empty tag

# Create frames
frac="0.5"
hc keybind Mod4-Control-h split left $frac   #Create frame to left
hc keybind Mod4-Control-j split right $frac  #Create frame to right
hc keybind Mod4-Control-k split top $frac    #Create frame up
hc keybind Mod4-Control-l split bottom $frac #Create frame down
hc keybind Mod4-Control-space split explode  #Explode current frame

# resizing frames
resizestep=0.02
hc keybind Mod4-Mod1-h resize left +$resizestep  #Resize frame leftwards
hc keybind Mod4-Mod1-j resize down +$resizestep  #Resize frames downwards
hc keybind Mod4-Mod1-k resize up +$resizestep    #Resize frame upwards
hc keybind Mod4-Mod1-l resize right +$resizestep #Resize frame rightwards

# Misc. frame ctrls
hc keybind Mod4-f set always_show_frame toggle #Toggle frame visibility
hc keybind Mod4-Control-r rotate               #Rotate fram layout by 90 degrees

# Adjust gaps
hc keybind Mod4-minus spawn ~/.config/herbstluftwm/scripts/gap_adjust.sh -win       #Minus window gap
hc keybind Mod4-equal spawn ~/.config/herbstluftwm/scripts/gap_adjust.sh +win       #Plus window gap
hc keybind Mod4-Shift-minus spawn ~/.config/herbstluftwm/scripts/gap_adjust.sh -frm #Minus frame gap
hc keybind Mod4-Shift-equal spawn ~/.config/herbstluftwm/scripts/gap_adjust.sh +frm #Plus frame gap
hc keybind Mod4-BackSpace spawn ~/.config/herbstluftwm/scripts/gap_adjust.sh        #Reset gaps

# swapping frames (actually just transferring windows across frames)
hc keybind Mod4-Shift-Ctrl-l \
    substitute OLDWIN clients.focus.winid chain \
    , focus -e right \
    , substitute NEWWIN clients.focus.winid \
    spawn ~/.config/herbstluftwm/scripts/swapwins.sh OLDWIN NEWWIN left
hc keybind Mod4-Shift-Ctrl-h \
    substitute OLDWIN clients.focus.winid chain \
    , focus -e left \
    , substitute NEWWIN clients.focus.winid \
    spawn ~/.config/herbstluftwm/scripts/swapwins.sh OLDWIN NEWWIN right
hc keybind Mod4-Shift-Ctrl-k \
    substitute OLDWIN clients.focus.winid chain \
    , focus -e up \
    , substitute NEWWIN clients.focus.winid \
    spawn ~/.config/herbstluftwm/scripts/swapwins.sh OLDWIN NEWWIN down
hc keybind Mod4-Shift-Ctrl-j \
    substitute OLDWIN clients.focus.winid chain \
    , focus -e down \
    , substitute NEWWIN clients.focus.winid \
    spawn ~/.config/herbstluftwm/scripts/swapwins.sh OLDWIN NEWWIN up

# Load keychains
~/.config/herbstluftwm/keychain.sh

# remove any existing mouse bindings
hc mouseunbind --all
hc mousebind Mod4-Button1 move
hc mousebind Mod4-Button2 zoom
hc mousebind Mod4-Button3 resize

# tags
tag_names=({1..9} 0)
tag_keys=({1..9} 0)
# Need this before tag creation
hc set default_frame_layout 'max'
hc substitute ALGO settings.default_frame_layout \
    foreach T tags.by-name. \
    sprintf ATTR '%c.tiling.root.algorithm' T \
    set_attr ATTR ALGO

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}"; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ]; then
        #hc keybind "$Mod-$key" use_index "$i" #Focus tag at number
        hc keybind "Mod4-$key" substitute PRE tags.focus.index chain + use_index "$i" + or , compare tags.focus.index != PRE , use_previous #Focus tag at number
        hc keybind "Mod4-Shift-$key" move_index "$i"                                                                                        #Move focus window to tag at number
    fi
done

# theme
hc set hide_covered_windows false
hc set frame_border_active_color '#af875f'
hc set frame_border_normal_color '#1c1c1c'
hc set frame_border_inner_color '#424242'
hc set frame_border_inner_width 5
hc set frame_border_width 8
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 12
hc set frame_padding 0
hc set focus_follows_mouse 1
hc set snap_gap 12

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc attr theme.minimal.reset 1

hc attr theme.title_when 'multiple_tabs'
hc attr theme.title_align 'center'
hc attr theme.title_color '#dfdfaf'
hc attr theme.title_font 'monospace'
hc attr theme.title_height 25
hc attr theme.title_depth 18
hc attr theme.border_width 0
hc attr theme.tab_color '#424242'
#hc attr theme.inner_width 5
#hc attr theme.outer_width 3
hc attr theme.color '#1c1c1c'
hc attr theme.active.color '#1c1c1c'
hc attr theme.normal.outer_color '#1c1c1c'
hc attr theme.active.outer_color '#af875f'
hc attr theme.inner_color '#424242'
hc attr theme.floating.border_width 8
hc attr theme.floating.inner_width 5
hc attr theme.floating.outer_width 3
hc attr theme.floating.inner_color '#3a3a3a'
hc attr theme.floating.active.outer_color '#af875f'
hc attr theme.floating.normal.outer_color '#1c1c1c'
hc attr theme.urgent.outer_color '#af5f5f'

#To hide frame at startup
hc set frame_active_opacity 0

hc set window_gap 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set focus_stealing_prevention true
hc set mouse_recenter_gap 0
hc set focus_crosses_monitor_boundaries 1
hc set swap_monitors_to_get_tag 0
hc set raise_on_focus 1
hc pad 0 0 0 0 0

# rules
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule instance=dropdown floating=on focus=on
hc rule class=Nsxiv floating=on floatplacement=center focus=on #floating_geometry=1824x1026+40+19
hc rule class=mpv floating=on floatplacement=center focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on floatplacement=center
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class=qutebrowser tag=1
hc rule title=mutt tag=2
hc rule title=vit tag=2
hc rule title=ikhal tag=2
hc rule class=Zathura tag=3
hc rule title=weechat tag=6
hc rule title=Music tag=7 #fix me

# unlock, just to be sure
hc unlock

herbstclient set tree_style '■┃ ┣┗■━┓'

if hc silent new_attr bool my_not_first_autostart; then
    # Autostart
    # Load previously saved session (if one was created)
    if [ -f ~/.config/herbstluftwm/sessions/saved_session ]; then
        ~/.config/herbstluftwm/scripts/loadstate.sh &
    fi

    # Restart task spool list if one exists
    if [ -s $TS_SAVELIST ]; then
        $TS_SAVELIST && truncate -s 0 $TS_SAVELIST
    fi

    # Run these programs as user services
    uid=$(id -u)
    pgrep -U $uid runsv && pkill -U $uid runsv
    setsid runsvdir -P ~/.local/service &

    # Startup bar; didnt work great as a user service
    setsid sbar.sh &

    # Refresh dbus session address in cron
    crontab <(crontab -l | sed "s|DBUS_SESSION_BUS_ADDRESS=.*|DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS|")

    # Things that require an internet connection
    while :; do
        [ "$(cat /sys/class/net/wlp5s0/carrier)" -eq 1 ] && break
    done
    network=$(iwctl station wlp5s0 show | grep 'Connected network' | xargs | cut -d' ' -f3-)
    case "$network" in
    Ollies*Network)
        sv up ~/.local/service/synergy
        ;;
    *)
        sudo -A wg-quick up barbarossvpn
        ;;
    esac
fi

# do multi monitor setup here, e.g.:
# Auto start only once
#hc set_monitors 1366x768+0+0 1280x800+1366+0
# or simply:
hc detect_monitors
