#!/usr/bin/env bash
########################################################
#
#    ▄█    █▄     ▄█        ▄█     █▄    ▄▄▄▄███▄▄▄▄
#   ███    ███   ███       ███     ███ ▄██▀▀▀███▀▀▀██▄
#   ███    ███   ███       ███     ███ ███   ███   ███
#  ▄███▄▄▄▄███▄▄ ███       ███     ███ ███   ███   ███
# ▀▀███▀▀▀▀███▀  ███       ███     ███ ███   ███   ███
#   ███    ███   ███       ███     ███ ███   ███   ███
#   ███    ███   ███▌    ▄ ███ ▄█▄ ███ ███   ███   ███
#   ███    █▀    █████▄▄██  ▀███▀███▀   ▀█   ███   █▀
#                ▀
#
#######################################################
# Make interrupt signals do nothing.
trap '' INT TSTP

hc() {
    herbstclient "$@"
}

hc emit_hook reload
hc lock

# Dat wallpaper tho
noisewall "#452f2f"

#Load bindings sequentially, but lazily
{
    # Load keybinds/mousebinds
    ~/.config/herbstluftwm/bindings.sh

    # Load keychains
    ~/.config/herbstluftwm/keychain.sh
} &

# tags
tag_names=({1..9} 0)
tag_keys=({1..9} 0)
# Need this before tag creation
hc set default_frame_layout 'max'
hc substitute ALGO settings.default_frame_layout \
    foreach T tags.by-name. \
    sprintf ATTR '%c.tiling.root.algorithm' T \
    set_attr ATTR ALGO

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}"; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ]; then
        #hc keybind "$Mod-$key" use_index "$i" #Focus tag at number
        hc keybind "Mod4-$key" substitute PRE tags.focus.index chain + use_index "$i" + or , compare tags.focus.index != PRE , use_previous #Focus tag at number
        hc keybind "Mod4-Shift-$key" move_index "$i"                                                                                        #Move focus window to tag at number
    fi
done

# theme
hc set hide_covered_windows false
hc set frame_border_active_color '#af875f'
hc set frame_border_normal_color '#1c1c1c'
hc set frame_border_inner_color '#424242'
hc set frame_border_inner_width 5
hc set frame_border_width 8
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 12
hc set frame_padding 0
hc set focus_follows_mouse 1
hc set snap_gap 12

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc attr theme.minimal.reset 1

hc attr theme.title_when 'multiple_tabs'
hc attr theme.title_align 'center'
hc attr theme.title_color '#dfdfaf'
hc attr theme.title_font 'monospace'
hc attr theme.title_height 25
hc attr theme.title_depth 18
hc attr theme.border_width 0
hc attr theme.tab_color '#424242'
#hc attr theme.inner_width 5
#hc attr theme.outer_width 3
hc attr theme.color '#1c1c1c'
hc attr theme.active.color '#1c1c1c'
hc attr theme.normal.outer_color '#1c1c1c'
hc attr theme.active.outer_color '#af875f'
hc attr theme.inner_color '#424242'
hc attr theme.floating.border_width 8
hc attr theme.floating.inner_width 5
hc attr theme.floating.outer_width 3
hc attr theme.floating.inner_color '#3a3a3a'
hc attr theme.floating.active.outer_color '#af875f'
hc attr theme.floating.normal.outer_color '#1c1c1c'
hc attr theme.urgent.outer_color '#af5f5f'

#To hide frame at startup
hc set frame_active_opacity 0

hc set window_gap 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set focus_stealing_prevention true
hc set mouse_recenter_gap 0
hc set focus_crosses_monitor_boundaries 1
hc set swap_monitors_to_get_tag 0
hc set raise_on_focus 1
#hc pad 0 0 0 0 0

# rules
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule instance=dropdown floating=on focus=on
hc rule class=Nsxiv floating=on floatplacement=center focus=on
hc rule class=mpv floating=on floatplacement=center focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on floatplacement=center
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class=qutebrowser tag=1
hc rule title=mutt tag=2
hc rule title=vit tag=2
hc rule title=ikhal tag=2
hc rule class=Zathura tag=4
hc rule class=Steam tag=5 floating=on floatplacement=center
hc rule title=weechat tag=6
hc rule title=Music tag=7 #fix me

# unlock, just to be sure
for i in seq $(hc get monitors_locked); do
    hc unlock
done

herbstclient set tree_style '■┃ ┣┗■━┓'

# Autostart
if hc silent new_attr bool my_not_first_autostart; then
    # Load previously saved session (if one was created)
    if [ -f ~/.config/herbstluftwm/sessions/saved_session ]; then
        ~/.config/herbstluftwm/scripts/loadstate.sh &
    fi

    # Restart task spool list if one exists
    if [ -s $TS_SAVELIST ]; then
        $TS_SAVELIST && truncate -s 0 $TS_SAVELIST
    fi

    # Run these programs as user services
    uid=$(id -u)
    pgrep -U $uid runsv && pkill -U $uid runsv
    setsid -f runsvdir -P ~/.local/service

    # Launch bar
    ~/.config/yambar/launch.sh

    # Things that require an internet connection
    while :; do
        [ "$(cat /sys/class/net/wlp5s0/carrier)" -eq 1 ] && break
    done
    network=$(iwctl station wlp5s0 show | grep 'Connected network' | xargs | cut -d' ' -f3-)
    case "$network" in
    Ollies*Network)
        sv start ~/.local/service/barrier
        ;;
    *)
        sudo -A wg-quick up barbarossvpn
        ;;
    esac

    #On startup, check for any new mails
    mailsync

fi

# do multi monitor setup here, e.g.:
# Auto start only once
#hc set_monitors 1366x768+0+0 1280x800+1366+0
# or simply:
hc detect_monitors
