#!/bin/sh

# Do nothing if interrupted
trap '' INT TSTP

userresources=$HOME/.config/x11/Xresources
usermodmap=$HOME/.config/x11/Xmodmap

# merge in defaults
[ -f "$userresources" ] && xrdb -merge "$userresources"
#[ -f "$usermodmap" ] && xmodmap "$usermodmap"

# Just to make sure my profile settings are loaded
[ -f /etc/profile ] && . /etc/profile
[ -f ~/.config/x11/xprofile ] && . ${HOME}/.config/x11/xprofile

# X settings
xset +fp ~/.local/share/fonts/misc,/usr/share/fonts/misc,/usr/share/fonts/X11/spleen
xset dpms 300 #Blank screen after 5 minutes (same time as lock kicks in)
xinput disable "Elan Touchpad"
hsetroot -solid '#1c1c1c'

# Need to start gpg agent before lock screen for pam-gnupg
gpg-connect-agent /bye

# launches a session dbus instance
[ -z "$DBUS_SESSION_BUS_ADDRESS" ] && eval $(dbus-launch --sh-syntax --exit-with-session)

lock &
sleep 0.5
exec herbstluftwm --locked
