box_draw_dark: &box_draw_dark
  margin: 8
  deco:
    stack:
      - background: 
          color: 262626ff
      - underline:
          size: 6
          color: 1c1c1cff
      - overline:
          size: 6
          color: 1c1c1cff

box_draw_light: &box_draw_light
  margin: 8
  deco:
    stack:
      - background: 
          color: 424242ff
      - underline:
          size: 6
          color: 1c1c1cff
      - overline:
          size: 6
          color: 1c1c1cff

bar:
  location: top
  monitor: HDMI-2
  height: 36
  foreground: dfdfafff
  background: 1c1c1cff
  margin: 6
  spacing: 4
  font: Spleen:pixelsize=16:file=/usr/share/fonts/X11/spleen/spleen-8x16.pcf.gz,Siji:pixelsize=10,Unifont:pixelsize=16,Twitter Color Emoji:pixelsize=14
  border:
    bottom-width: 3
    color: 424242ff

  left:
    - label:
        content: 
          - string: 
              text: 
              on-click: launch
              foreground: af5f5fff
              <<: *box_draw_light
    - script:
        path: /home/barbaross/.config/yambar/scripts/hlwm.sh
        anchors:
          - occupied: &occupied 
              foreground: dfdfafff
              <<: *box_draw_light
          - focused: &focused 
              foreground: af875fff
              <<: *box_draw_dark
          - active: &active 
              foreground: 87afafff
              <<: *box_draw_light
          - urgent: &urgent 
              foreground: af5f5fff
              <<: *box_draw_light
          - default: &empty 
              foreground: 262626ff
              <<: *box_draw_light
        content:
          list:
            spacing: 0
            items:
              - map:
                  tag: tag_1
                  values:
                    f:
                      string:
                        text: 1
                        on-click: herbstclient use 1
                        <<: *focused
                    o:
                      string:
                        text: 1
                        on-click: herbstclient use 1
                        <<: *occupied
                    u:
                      string:
                        text: 1
                        on-click: herbstclient use 1
                        <<: *urgent
                    a:
                      string:
                        text: 1
                        on-click: herbstclient use 1
                        <<: *active
                    e:
                      string:
                        text: 1
                        on-click: herbstclient use 1
                        <<: *empty
              - map:
                  tag: tag_2
                  values:
                    f:
                      string:
                        text: 2
                        on-click: herbstclient use 2
                        <<: *focused
                    o:
                      string:
                        text: 2
                        on-click: herbstclient use 2
                        <<: *occupied
                    u:
                      string:
                        text: 2
                        on-click: herbstclient use 2
                        <<: *urgent
                    a:
                      string:
                        text: 2
                        on-click: herbstclient use 2
                        <<: *active
                    e:
                      string:
                        text: 2
                        on-click: herbstclient use 2
                        <<: *empty
              - map:
                  tag: tag_3
                  values:
                    f:
                      string:
                        text: 3
                        on-click: herbstclient use 3
                        <<: *focused
                    o:
                      string:
                        text: 3
                        on-click: herbstclient use 3
                        <<: *occupied
                    u:
                      string:
                        text: 3
                        on-click: herbstclient use 3
                        <<: *urgent
                    a:
                      string:
                        text: 3
                        on-click: herbstclient use 3
                        <<: *active
                    e:
                      string:
                        text: 3
                        on-click: herbstclient use 3
                        <<: *empty
              - map:
                  tag: tag_4
                  values:
                    f:
                      string:
                        text: 4
                        on-click: herbstclient use 4
                        <<: *focused
                    o:
                      string:
                        text: 4
                        on-click: herbstclient use 4
                        <<: *occupied
                    u:
                      string:
                        text: 4
                        <<: *urgent
                    a:
                      string:
                        text: 4
                        on-click: herbstclient use 4
                        <<: *active
                    e:
                      string:
                        text: 4
                        on-click: herbstclient use 4
                        <<: *empty
              - map:
                  tag: tag_5
                  values:
                    f:
                      string:
                        text: 5
                        on-click: herbstclient use 5
                        <<: *focused
                    o:
                      string:
                        text: 5
                        on-click: herbstclient use 5
                        <<: *occupied
                    u:
                      string:
                        text: 5
                        on-click: herbstclient use 5
                        <<: *urgent
                    a:
                      string:
                        text: 5
                        on-click: herbstclient use 5
                        <<: *active
                    e:
                      string:
                        text: 5
                        on-click: herbstclient use 5
                        <<: *empty
              - map:
                  tag: tag_6
                  values:
                    f:
                      string:
                        text: 6
                        on-click: herbstclient use 6
                        <<: *focused
                    o:
                      string:
                        text: 6
                        on-click: herbstclient use 6
                        <<: *occupied
                    u:
                      string:
                        text: 6
                        on-click: herbstclient use 6
                        <<: *urgent
                    a:
                      string:
                        text: 6
                        on-click: herbstclient use 6
                        <<: *active
                    e:
                      string:
                        text: 6
                        on-click: herbstclient use 6
                        <<: *empty
              - map:
                  tag: tag_7
                  values:
                    f:
                      string:
                        text: 7
                        on-click: herbstclient use 7
                        <<: *focused
                    o:
                      string:
                        text: 7
                        on-click: herbstclient use 7
                        <<: *occupied
                    u:
                      string:
                        text: 7
                        on-click: herbstclient use 7
                        <<: *urgent
                    a:
                      string:
                        text: 7
                        on-click: herbstclient use 7
                        <<: *active
                    e:
                      string:
                        text: 7
                        on-click: herbstclient use 7
                        <<: *empty
              - map:
                  tag: tag_8
                  values:
                    f:
                      string:
                        text: 8
                        on-click: herbstclient use 8
                        <<: *focused
                    o:
                      string:
                        text: 8
                        on-click: herbstclient use 8
                        <<: *occupied
                    u:
                      string:
                        text: 8
                        on-click: herbstclient use 8
                        <<: *urgent
                    a:
                      string:
                        text: 8
                        on-click: herbstclient use 8
                        <<: *active
                    e:
                      string:
                        text: 8
                        on-click: herbstclient use 8
                        <<: *empty
              - map:
                  tag: tag_9
                  values:
                    f:
                      string:
                        text: 9
                        on-click: herbstclient use 9
                        <<: *focused
                    o:
                      string:
                        text: 9
                        on-click: herbstclient use 9
                        <<: *occupied
                    u:
                      string:
                        text: 9
                        on-click: herbstclient use 9
                        <<: *urgent
                    a:
                      string:
                        text: 9
                        on-click: herbstclient use 9
                        <<: *active
                    e:
                      string:
                        text: 9
                        on-click: herbstclient use 9
                        <<: *empty
              - map:
                  tag: tag_0
                  values:
                    f:
                      string:
                        text: 0
                        on-click: herbstclient use 0
                        <<: *focused
                    o:
                      string:
                        text: 0
                        on-click: herbstclient use 0
                        <<: *occupied
                    u:
                      string:
                        text: 0
                        on-click: herbstclient use 0
                        <<: *urgent
                    a:
                      string:
                        text: 0
                        on-click: herbstclient use 0
                        <<: *active
                    e:
                      string:
                        text: 0
                        on-click: herbstclient use 0
                        <<: *empty
    - script:
        path: /home/barbaross/.config/yambar/scripts/notif.sh
        content:
          list:
            spacing: 4
            items:
              - map:
                  tag: history
                  values:
                    true:
                      string:
                        text: " NOTIF HISTORY:"
                        foreground: dfaf87ff
                    false:
                      string:
                        text: " NOTIFICATION:"
                        foreground: dfaf87ff
              - map:
                  tag: notif
                  default:
                    string:
                      text: "{notif}"
                  values:
                    clear:
                      empty: {}

  right:
    - script:
        path: /home/barbaross/.config/yambar/scripts/tray.sh
        content:
          list:
            spacing: 0
            items:
              - map:
                  tag: bluetooth
                  values:
                    0:
                      string:
                        text: 
                        foreground: 87afafff
                        <<: *box_draw_dark
                    1:
                      empty: {}
              - map:
                  tag: caffeine
                  values:
                    true:
                      string:
                        text: 
                        foreground: af8787ff
                        <<: *box_draw_dark
                    false:
                      empty: {}

              - map:
                  tag: kb
                  values:
                    colemak:
                      string:
                        text: ''
                        foreground: af5f5fff
                        <<: *box_draw_dark
                    qwerty:
                      empty: {}

              - map:
                  tag: vpn
                  values:
                    none:
                      empty: {}
                    wireguard:
                      string:
                        text: 
                        foreground: af5f5fff
                        <<: *box_draw_dark
                    openvpn:
                      string:
                        text: 
                        foreground: dfaf87ff
                        <<: *box_draw_dark
                    wireguardopenvpn:
                      string:
                        text: 
                        foreground: af875fff
                        <<: *box_draw_dark

    - battery:
        name: BAT0
        poll-interval: 30
        anchors:
          discharging: &discharging
            list:
              spacing: 0
              items:
                - ramp:
                    tag: capacity
                    on-click: powertime
                    <<: *box_draw_light
                    items:
                      - string: {text: , foreground: 87875fff}
                      - string: {text: , foreground: 87875fff}
                      - string: {text: , foreground: 87875fff}
                      - string: {text: , foreground: 87875fff}
                      - string: {text: , foreground: 87875fff}
                      - string: {text: , foreground: 87875fff}
                      - string: {text: , foreground: 87875fff}
                      - string: {text: , foreground: 87875fff}
                      - string: {text: , foreground: 87875fff}
                      - string: {text: , foreground: 87875fff}
                - string: 
                    text: "{capacity}%"
                    on-click: powertime
                    <<: *box_draw_dark
          full: &full
            list:
              spacing: 0
              items:
                - string: 
                    text: 
                    on-click: powertime
                    foreground: 87875fff
                    <<: *box_draw_light
                - string: 
                    text: "Full"
                    on-click: powertime
                    <<: *box_draw_dark
        content:
          map:
            tag: state
            values:
              unknown:
                <<: *discharging
              discharging:
                <<: *discharging
              charging:
                list:
                  spacing: 0
                  items:
                    - string: 
                        text: 
                        on-click: powertime
                        foreground: 87875fff
                        <<: *box_draw_light
                    - string: 
                        text: "{capacity}%"
                        on-click: powertime
                        <<: *box_draw_dark
              full:
                <<: *full
              not charging:
                <<: *full
    - alsa:
        card: default
        mixer: Master
        content:
          map:
            tag: muted
            values:
              true:
                list:
                  spacing: 0
                  items:
                    - string: 
                        text: 
                        foreground: 626262ff
                        <<: *box_draw_light
                    - string: 
                        text: "{percent}%"
                        <<: *box_draw_dark
              false:
                list:
                  spacing: 0
                  items:
                    - ramp:
                        tag: percent
                        <<: *box_draw_light
                        items:
                          - string: {text: , foreground: 87afafff}
                          - string: {text: , foreground: 87afafff}
                          - string: {text: , foreground: 87afafff}
                          - string: {text: , foreground: 87afafff}
                          - string: {text: , foreground: 87afafff}
                    - string: 
                        text: "{percent}%"
                        <<: *box_draw_dark
    - backlight: 
        name: intel_backlight
        content:
          list:
            spacing: 0
            items: 
              - ramp:
                  tag: percent
                  <<: *box_draw_light
                  items:
                    - string: {text: , foreground: af875fff}
                    - string: {text: , foreground: af875fff}
                    - string: {text: , foreground: af875fff}
                    - string: {text: , foreground: af875fff}
              - string: 
                  text: "{percent}%"
                  <<: *box_draw_dark
    - network:
        name: wlp5s0
        content:
          map:
            tag: state
            default: {string: {text: , foreground: 626262ff}}
            values:
              down:
                list:
                  spacing: 0
                  items:
                    - string: 
                        text: 
                        foreground: 626262ff
                        <<: *box_draw_light
                    - string:
                        text: D/C
                        <<: *box_draw_dark
              up:
                list:
                  spacing: 0
                  items:
                    - ramp:
                        tag: signal
                        <<: *box_draw_light
                        min: -90
                        max: -30
                        items:
                          - string: {text: , foreground: af8787ff}
                          - string: {text: , foreground: af8787ff}
                          - string: {text: , foreground: af8787ff}
                          - string: {text: , foreground: af8787ff}
                          - string: {text: , foreground: af8787ff}
                    - string: 
                        text: "{ssid}"
                        <<: *box_draw_dark
    - clock:
        date-format: "%A, %B %d"
        content:
          list:
            spacing: 0
            items:
              - string: 
                  text:  
                  foreground: af875fff
                  <<: *box_draw_light
              - string: 
                  text: "{date}"
                  <<: *box_draw_dark
    - clock:
        time-format: "%I:%M %p"
        content:
          list:
            spacing: 0
            items:
              - string: 
                  text: 
                  foreground: 87875fff
                  <<: *box_draw_light
              - string: 
                  text: "{time}"
                  <<: *box_draw_dark
