#!/bin/sh

coords=$(curl -s 'https://location.services.mozilla.com/v1/geolocate?key=geoclue' | jq '.location.lat, .location.lng' | tr '\n' ':' | sed 's/:$//')

exec wlsunset -l "$(echo $coords | cut -d ':' -f1)" -L "$(echo $coords | cut -d ':' -f2)"
