#!/bin/sh

###############################
#
# ░█▀▄░█▀▀░█▀█░█░█░█▄█░█▀▄░█▀▀
# ░█▀▄░▀▀█░█▀▀░█▄█░█░█░█▀▄░█░░
# ░▀▀░░▀▀▀░▀░░░▀░▀░▀░▀░▀░▀░▀▀▀
#
###############################

# Do nothing if interrupted
trap '' INT TSTP

pgrep -x sxhkd >/dev/null || sxhkd &

###Config

bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor eDP1 -d          

bspc config border_width 3
bspc config top_padding 0
bspc config right_padding 8
bspc config left_padding 8
bspc config bottom_padding 8
bspc config window_gap 16

. "${HOME}/.config/bspwm/colorschemes/alduin.sh"
bspc config focused_border_color "$color3"
bspc config normal_border_color "$color16"
bspc config active_border_color "$color6"
bspc config presel_feedback_color "$color3"
bspc config split_ratio 0.50
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config focus_follows_pointer true
#bspc config external_rules_command "$HOME/.config/bspwm/external_rules.sh"
bspc config pointer_follows_focus false
bspc config single_monocle false
bspc config ignore_ewmh_focus false

###Rules
# Cleanup
bspc rule -r '*'

# State rules
#bspc rule -a "Emacs" state=tiled
bspc rule -a St:dropdown state=floating #sticky=on
bspc rule -a "Sxiv" state=fullscreen
bspc rule -a "mpv" state=floating
bspc rule -a "Zathura" state=tiled

# Assignment rules
bspc rule -a "qutebrowser" desktop=^1 follow=on
bspc rule -a *:*:aerc desktop=^2 follow=on
bspc rule -a *:*:ikhal desktop=^2 follow=on
bspc rule -a *:*:vit desktop=^2 follow=on
#bspc rule -a libreoffice-* desktop=^3 follow=on #Fix me
bspc rule -a "Zathura" desktop=^3 follow=on
bspc rule -a *:*:irssi desktop=^6 follow=on
bspc rule -a *:*:slack-term desktop=^6 follow=on
bspc rule -a *:*:Spotify desktop=^7 follow=on

### Non-bspwm specific settings
xset s 180 120
xset dpms 305
xset r rate 440 50
xset -b
xsetroot -cursor_name left_ptr

###Application startup
startup_lock_file=/tmp/bspwm-startup.lock
if [ ! -f $startup_lock_file ]; then
    touch $startup_lock_file
    xwallpaper --tile ~/Pictures/antigen.png
    #xwallpaper --zoom ~/Pictures/upscaleddarksouls.png
    #hashwall -b "#121212" -f "#262626" -s 8 -r 64
    /usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
    unclutter &
    clipmenud &
    xss-lock -n dim-screen.sh -l -- lock &
    idle.sh 10 "systemctl suspend-then-hibernate" &

    # Things that require an internet connection
    nm-online -q
    network=$(nmcli -g IN-USE,SSID d wifi list | grep "*" | cut -d':' -f2)
    matches=$(echo "$network" | grep 'Ollies_Network\|Ollies_5ghz_Network')
    #if [[ "$(nmcli -g IN-USE,SSID d wifi list | grep "*" | cut -d':' -f2)" =~ ^(Ollies_Network|Ollies_5ghz_Network)$ ]]; then
    if [ "$matches" = "Ollies_Network" ] || [ "$matches" = "Ollies_5ghz_Network" ]; then
        synergyc 192.168.0.16 &
    else
        nmcli c u acer
    fi

    distraction_mode_check.sh &
    weather.sh &
    gitwatch -r pi@192.168.0.18:/mnt/fd1/repos/thonkpad-dotfiles /home/barbarossa/Public/thonkpad-dotfiles &
    syncthing -no-browser &
    redshift -l $(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | jq '.location.lat, .location.lng' | tr '\n' ':' | sed 's/:$//') &
fi
