backend = "alsa"
backend_device = "default"
use_nerdfont = false
notify = false
volnorm = false

[theme]
background = "default"
primary = "white"
secondary = "red"
title = "red"
playing = "yellow"
playing_selected = "red"
playing_bg = "black"
highlight = "yellow"
highlight_bg = "black"
error = "white"
error_bg = "yellow"
statusbar = "yellow"
statusbar_progress = "magenta"
statusbar_bg = "black"
cmdline = "white"
cmdline_bg = "black"
search_match = "red"
