#!/bin/sh

# Do nothing if interrupted
trap '' INT TSTP

userresources=$HOME/.config/x11/Xresources

# merge in defaults
[ -f "$userresources" ] && xrdb -merge "$userresources"

# Just to make sure my profile settings are loaded
[ -f /etc/profile ] && . /etc/profile
[ -f ~/.config/bash/bash_profile ] && . ~/.config/bash/bash_profile
[ -f ~/.config/x11/xprofile ] && . ~/.config/x11/xprofile

# X settings
xset +fp ~/.local/share/fonts/misc
xset +fp /usr/share/fonts/misc
xset s 180 119 #with xss-lock, dim screen after 3 minutes, then lock 2 minutes later
xset dpms 300  #with xss-lock, blank screen shortly after locking
xset r rate 440 50
xset -b
xinput disable "Elan Touchpad"
xcape -e 'Shift_L=Escape'

# Need to start gpg agent before lock screen for pam-gnupg
gpg-connect-agent /bye

## Ensure ssh-agent is running
SSH_ENV="$HOME/.ssh/agent-environment"

start_agent() {
	echo "Initialising new SSH agent..."
	/usr/bin/ssh-agent | sed 's/^echo/#echo/' >"${SSH_ENV}"
	echo succeeded
	chmod 600 "${SSH_ENV}"
	. "${SSH_ENV}" >/dev/null
	/usr/bin/ssh-add
}

# Source SSH settings, if applicable
if [ -f "${SSH_ENV}" ]; then
	. "${SSH_ENV}" >/dev/null
	ps ${SSH_AGENT_PID} | grep ssh-agent$ >/dev/null || {
		start_agent
	}
else
	start_agent
fi

# needed to create a dbus session address env var
[ -z $DBUS_SESSION_BUS_ADDRESS ] && eval $(dbus-launch --sh-syntax --exit-with-session)

lock &
sleep 0.3
exec herbstluftwm --locked
